# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_author',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book_author',
            name='book',
        ),
        migrations.AddField(
            model_name='author',
            name='all_books',
            field=models.ManyToManyField(related_name='authors', to='book_authors.Book'),
        ),
        migrations.DeleteModel(
            name='Book_Author',
        ),
    ]
