# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='book_reviews.User'),
            preserve_default=False,
        ),
    ]
